### ISSUE TITLE
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. Object {

### ISSUE THREAD

**Issue by soly2014** [hyochan/react-native-masonry-list#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hyochan** [comment]
@soly2014 This is interesting. I've just gone through [react-native-virtualized-masonry](https://github.com/iftechio/react-native-virtualized-masonry/blob/master/src/index.tsx) and this just wraps the whole thing inside the `FlatList` instead of `ScrollView`.

Do you think this would solve the problem?

**Comment by hyochan** [comment]
I think this is rather related to https://stackoverflow.com/questions/44743904/virtualizedlist-you-have-a-large-list-that-is-slow-to-update. Check if you are not re-rendering `react-native-masonry-list`.

Please come back if you still have a problem.

**Comment by soly2014** [comment]
hey @hyochan thank u very much. yes i think using FlatList instead of ScrollView will solve the problem

**Comment by hyochan** [comment]
Actually I dont currently agree. Please refer to 
https://stackoverflow.com/questions/44743904/virtualizedlist-you-have-a-large-list-that-is-slow-to-update

And see if you can solve the problem.
